# -*- coding: utf-8 -*-
"""EXNO2DS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ymCTA1j5RI-UKnnpBC6gOUJWzDfOtFCs
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
dt=pd.read_csv("titanic_dataset.csv")
dt

dt.info()

#DISPLAY NO OF ROWS AND COLUMNS
dt.shape
#SET PASSENGER ID AS INDEX COLUMN
dt.set_index("PassengerId",inplace=True)
dt.describe()
#CATEGORICAL DATA ANALYSIS
# USE VALUE COUNT FUNCTION AND PERFROM CATEGORICAL ANALYSIS
dt.nunique()
dt["Survived"].value_counts()
per=(dt["Survived"].value_counts()/dt.shape[0]*100).round(2)
per
#UNIVARIATE ANALYSIS
# USE COUNTPLOT AND PERFORM UNIVARIATE ANALYSIS FOR THE "SURVIVED" COLUMN IN TITANIC DATASET
sns.countplot(data=dt,x="Survived")
# IDENTIFY UNIQUE VALUES IN "PASSENGER CLASS" COLUMN
dt.Pclass.unique()
# RENAMING COLUMN
dt.rename(columns = {'Sex':'Gender'}, inplace = True)
dt
#BIVARIATE ANALYSIS**
sns.catplot(x="Gender",col="Survived",kind="count",data=dt,height=5,aspect=.7)
sns.catplot(x='Survived',hue="Gender",data=dt,kind="count")
dt.boxplot(column="Age",by="Survived")
sns.scatterplot(x=dt["Age"],y=dt["Fare"])
sns.jointplot(x="Age",y="Fare",data=dt)
#MULTIVARIATE ANALYSIS**
fig,ax1=plt.subplots(figsize=(8,5))
pt=sns.boxplot(ax=ax1,x='Pclass',y='Age',hue='Gender',data=dt)
# USE CATPLOT METHOD AND ANALYZE THREE COLUMNS(PCLASS,SURVIVED,GENDER)
pt=sns.boxplot(ax=ax1,x='Pclass',y='Age',hue='Gender',data=dt)
sns.catplot(data=dt,col="Survived",x="Gender",hue="Pclass",kind="count")
corr = dt.corr()
sns.heatmap(corr,annot=True)
sns.pairplot(dt)